### ISSUE TITLE
Note diary

### ISSUE THREAD

**Issue by JohanAnim** [nvaccess/addon-datastore#3435] opened 2024-05-09 15:26 UTC
### Download URL

https://github.com/JohanAnim/Note-diary/releases/download/2024.1.0/Note.diary.for.NVDA-2024.1.0.nvda-addon

### Source URL

https://github.com/JohanAnim/Note-diary

### Publisher

Johan G <gutierrezjohanantonio@gmail.com>

### Channel

stable

### License Name

GPL v3

### License URL

https://www.gnu.org/licenses/gpl-3.0.html

**Comment by JohanAnim** [comment] 2024-05-09 15:46
Hello,
I don't know why when I try to publish my plugin I get the following error:
Send json file / call-workflow-passing-data / verifySubmitter (3.11)
Failed in 7 seconds 1

Please help.

**Comment by seanbudd** [comment] 2024-05-10 06:10
@nvdaes - it looks like a regression has been introduced at some point preventing add-on Ids with spaces from being able to be submitted

Hi @JohanAnim - we're going to have to perform some maintainence before this add-on can be submitted. Alternatively, update the name field in your add-on manifest to remove the spaces e.g. "noteDiary" is a good add-on ID

**Comment by nvdaes** [comment] 2024-05-10 06:25
> it looks like a regression has been introduced at some point preventing add-on Ids with spaces from being able to be submitted

Maybe a regression, though I don't know other add-ons containing spaces in addonId. This add-on was updated, according to the log of the addon-datastore repo, on June, when submitters didn't need to be approved.

**Comment by XLTechie** [comment] 2024-05-10 06:51
@seanbudd Why DO we accept spaces in IDs anyway? Given how they are used, it seems like asking for trouble.

**Comment by lukaszgo1** [comment] 2024-05-10 07:11
We had this discussion before - see https://github.com/nvaccess/addon-datastore/issues/2037#issuecomment-1822656313. Given this comes up from time to time, perhaps we should have a documentation with reasoning. In the ideal world we would also have some kind of  tests, ensuring add-on ID's with spaces work, though I don't know if testing GitHub workflows is feasible.

**Comment by XLTechie** [comment] 2024-05-10 07:19
@lukaszgo1 So my understanding from that, is that we should allow spaces because some few add-ons will have to change name, and changing name is difficult?

@nvdaes's concern about the translation system still seems like a good reason not to allow spaces, as that system appears not to be going away soon as you speculated.

Maybe, instead, we should devise a more convenient way to rename add-ons? That is certainly a problem we are going to keep having, usually for other reasons than spaces.

**Comment by lukaszgo1** [comment] 2024-05-10 07:30
From https://github.com/nvaccess/nvda/discussions/15014:
> Deprecate add-on translation system, encouraging add-on authors to rely on other mainstream services or workflows to accept / process translations from the community. 
◦ Deprecation starts after NVDA 2023.3.
◦ Deprecation means no new add-on registrations.
◦ The service will be completely removed 1 year later or when all add-ons are off the system, which ever comes first. This includes hosting of add-on translations, and hosting of the old add-ons website.

Is there are any more up-todate info about translation systems for add-ons? In general it has several artificial limitations around naming, which IMO should be fixed in the system if it is going to stay. Also you said
> That is certainly a problem we are going to keep having, usually for other reasons than spaces.

Could you please provide examples of these 'other reasons'?

**Comment by nvdaes** [comment] 2024-05-10 13:08
Seems that this is produced when validate command is called, since after the space an argument is expected. The path maybe closed in quotes to see if this works.
I'm tryting to fix the double comment of the manual approval PR, so I'll test this too.

**Comment by seanbudd** [comment] 2024-05-13 06:51
Closing in favour of #3437

**Closed by seanbudd** 2024-05-13 06:51 UTC
Labels: autoSubmissionFromIssue
