### ISSUE TITLE
[Submit add-on]: 

### ISSUE THREAD

**Issue by Emil-18** [nvaccess/addon-datastore#3293] opened 2024-04-20 19:52 UTC
### Download URL

https://github.com/Emil-18/enhanced-object-navigation/releases/download/v0.1.1/enhancedObjectNavigation-0.1.1.nvda-addon

### Source URL

https://github.com/Emil-18/enhanced-object-navigation

### Publisher

Emil-18 <emilhesmyr@icloud.com>

### Channel

stable

### License Name

GPL v2

### License URL

https://www.gnu.org/licenses/gpl-2.0.html

**Comment by seanbudd** [comment] 2024-04-23 02:12
Closing as duplicate of #3291

**Closed by seanbudd** 2024-04-23 02:12 UTC
Labels: autoSubmissionFromIssue
